# Docker Compose configuration for Next.js app with Sakila MySQL
version: "3.8"

services:
  db:
    image: sakiladb/mysql:latest
    container_name: sakila-mysql
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@sakila-mysql:3306/${MYSQL_DATABASE}
    depends_on:
      - db
    volumes:
      - ./:/app

volumes:
  db_data:
